---
dictionary:
- Apparmor
- AutoYaST
- Autotools
- AutoPackages
- Bootloader
- Btrfs
- BuildRequires
- Builtins
- Byebug
- CIFS
- CIM
- CLI
- CMake
- CVE
- Changelog
- DASD
- DBus
- DNS
- Devel
- Eval
- FCoE
- FIXME
- FTPd
- Fibre
- FileSystem
- GCC
- GDB
- GPL
- Github
- Gtk
- HOWTO
- IBS
- IP
- IPL
- IUCV
- KVM
- Kerberos
- Kobliha's
- LGPL
- LGTM
- LIO
- LTS
- LXC
- Ladislav's
- LangAddOn
- Linux's
- Linuxrc
- Makefile
- MkDocs
- NEEDINFO
- NfsAutoClient
- NTP
- NVRA
- Ncurses
- Online
- OpenSLP
- POS
- POV
- Prolog
- PulseAudio
- PushButton
- PyYAML
- RDP
- README
- REPL
- REQ
- RPMS
- RPMs
- ReaR
- Refactoring
- RuboCop
- Rubydoc
- SCC
- SCRClose
- SCROpen
- SCRSetDefault
- SLE
- SMB
- SMT
- SOURCERPM
- SSSD
- ST L
- SUSE's
- SoftwareApplication
- TCL
- TFTP
- Trello
- USB
- VBox
- VM
- Veewee
- WIP
- Wiki
- Workflow
- XEN
- YP
- Yast
- ZFCP
- abovementioned
- afterwards
- apparmor
- aspell
- auth
- autoconf
- autoconfiguration
- autoinstallation
- autolinking
- automake
- autotools
- autoyast
- backport
- backporting
- backtrace
- bcond
- bootloader
- br
- break
- breakpoint
- bt
- bugzilla
- byebug
- bz
- cd
- cheatsheet
- checkin
- chroot
- chrooted
- ci
- cim
- cio
- cmdline
- conf
- config
- cvs
- dbus
- debian
- desc
- dev
- devtools
- dhcp
- dir
- dns
- docbook
- dpkg
- drbd
- endfor
- endif
- eval
- fcoe
- firstboot
- fontconfig
- gcc
- gdb
- geo
- GetModified
- github
- gitk
- gui
- hostnames
- http
- iSCSI
- iSNS
- idmapd
- inetd
- instserver
- iplb
- irb
- iscsi
- isns
- journalctl
- kdump
- laf
- ldap
- ldapcpplib
- libYUI
- libstorage
- liby
- libycp
- libyui
- lio
- localhost
- login
- lxc
- mailinglist
- metadata
- metapackage
- mkdocs
- multipath
- namespace
- navbar
- ncurses
- needinfo
- nfs
- nis
- ntp
- nux's p
- ok
- oneline
- online
- ons
- openQA
- opensuse
- openwsman
- operatingSystem
- pam
- partitioner
- perl
- plugin
- png
- pos
- qf
- rdp
- readthedocs
- refactoring
- reipl
- reiterate
- renderer
- rspec
- rubygem
- rubygems
- scr
- scrconf
- screenshot
- simplecov
- skelcd
- slp
- snapshotting
- sr
- src
- startshell
- stylesheets
- subcomponents
- sys
- sysconfig
- tftp
- tmp
- toolchain
- toplevel
- travis
- tui
- ui
- understandability
- url
- usr
- versa
- virtualization
- vm
- vsftpd
- wfm
- wiki
- xdg
- xinetd
- xml
- xsl
- ytrello
- zSeries
- NfsAutoClient
- textdomain
- Nfs
- ret
- func
- param
- ret
- elsif
- CreateDialog
- SetDesktopIcon
- FstabDialog
- CloseDialog
- EOF
- KDE
- RootOnly
- HasReadOnlyMode
- RootOnly
- AutoInst
- SortKey
- AutoInstClonable
- AutoLogResource
- sbin
- GenericName
- AutoClient
- sda
- Args
- AutoSequence
- SetModified
- WriteOnly
- AutoClient
- BootStorage
- Initrd
- PackagesProposal
- Autoyast
- AutoClient
- attr
- accessor
- PackagesProposal
- AddResolvables
- Initrd
- ModuleType
- AutoInstPath
- AutoInstClient
- AutoInstDataType
- AutoInstResource
- AutoInstRequires
- AutoInstMerge
- AutoInstMergeTypes
- datatypes
- AutoInstSchema
- rnc
- NG
- AutoInstOptional
- logfile
- jpeg
