# Site settings
title: YaST
description: powerfull installation and configuration tool for Linux
email: yast-devel@opensuse.org
baseurl: "/"
url: "http://0.0.0.0:4000"

# Build settings
markdown: kramdown
#permalink: pretty
